-- Warning: Generated by IPC system do not edit manually!
return {
  ["methods"] = {
    [1] = "core.change_directory(directory: string)",
    [2] = "core.open_directory(directory: string)",
    [3] = "core.open_file(file: string)"
  },
  ["last_update"] = 1717787598,
  ["replies"] = {},
  ["signals"] = {
    [1] = "core.tab_drag_received(file: string)",
    [2] = "core.tab_drag_start(file: string)",
    [3] = "core.tab_drag_stop()"
  },
  ["position"] = 1,
  ["id"] = "176303",
  ["messages"] = {},
  ["primary"] = true
}